// This is the code of the table we are going to show in the webpage with information of 
// other applicants

import React from 'react';
import "./Table.css";

const TableModule = () => {

return (
    <table>
        <tr>
            <td>ID</td>
            <td>Visa Type</td>
            <td>Visa Entry</td>
            <td>US Consulate</td>
            <td>Major</td>
            <td>Status</td>
            <td>Check Date</td>
            <td>Waiting Day(s)</td>
            <td>Details</td>
        </tr>
        <tr>
            <td>weojlkjs</td>
            <td>H1</td>
            <td>New</td>
            <td>Others</td>
            <td>Software Engineering</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>takeashot</td>
            <td>H1</td>
            <td>New</td>
            <td>BeiJing</td>
            <td>ECE</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>zhizhi</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>ShenYang</td>
            <td>Biostatistics</td>
            <td>Clear</td>
            <td>12/1/2022</td>
            <td>29</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>I-5求求了</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>BeiJing</td>
            <td>CS &amp; Math</td>
            <td>Clear</td>
            <td>12/1/2022</td>
            <td>4</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>kolokolo123</td>
            <td>B2</td>
            <td>New</td>
            <td>GuangZhou</td>
            <td>N/A</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>Elfsong</td>
            <td>B2</td>
            <td>New</td>
            <td>Others</td>
            <td>CS</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>kc</td>
            <td>H1</td>
            <td>New</td>
            <td>Toronto</td>
            <td>EE</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>快快快</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>ShangHai</td>
            <td>Data Science</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>ssfqqz</td>
            <td>H1</td>
            <td>Renewal</td>
            <td>MexicoCity</td>
            <td>必被check的那种</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>杨超越版ISS</td>
            <td>L1</td>
            <td>New</td>
            <td>BeiJing</td>
            <td>CS</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>无敌小可爱</td>
            <td>L1</td>
            <td>New</td>
            <td>GuangZhou</td>
            <td>Electrical Engineering</td>
            <td>Clear</td>
            <td>12/1/2022</td>
            <td>50</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>大家都快过</td>
            <td>J1</td>
            <td>New</td>
            <td>BeiJing</td>
            <td>Condensed Matter Physics</td>
            <td>Clear</td>
            <td>12/1/2022</td>
            <td>35</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>2023qianzheng</td>
            <td>H4</td>
            <td>New</td>
            <td>GuangZhou</td>
            <td>CS</td>
            <td>Pending</td>
            <td>12/1/2022</td>
            <td>57</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>lao_tsian</td>
            <td>B1</td>
            <td>New</td>
            <td>Others</td>
            <td>ChemE</td>
            <td>Clear</td>
            <td>12/1/2022</td>
            <td>50</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>AA00****FD</td>
            <td>B2</td>
            <td>New</td>
            <td>Others</td>
            <td>CS PhD</td>
            <td>Pending</td>
            <td>12/2/2022</td>
            <td>56</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>inc***@gmail.co</td>
            <td>H1</td>
            <td>New</td>
            <td>Toronto</td>
            <td>Computer Science</td>
            <td>Clear</td>
            <td>12/2/2022</td>
            <td>41</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>derek_831018</td>
            <td>O1</td>
            <td>New</td>
            <td>BeiJing</td>
            <td>N/A</td>
            <td>Pending</td>
            <td>12/2/2022</td>
            <td>56</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>阿弥陀佛</td>
            <td>H1</td>
            <td>Renewal</td>
            <td>ShangHai</td>
            <td>Chem Eng</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>45</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>lzy7977</td>
            <td>H1</td>
            <td>New</td>
            <td>ShangHai</td>
            <td>Computer Science</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>46</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>卡在家里</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>Others</td>
            <td>EE</td>
            <td>Pending</td>
            <td>12/5/2022</td>
            <td>53</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>kuaikuaixiaqian</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>Toronto</td>
            <td>Human-computer interactio</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>17</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>多伦多过过</td>
            <td>H1</td>
            <td>New</td>
            <td>Toronto</td>
            <td>Computer science</td>
            <td>Pending</td>
            <td>12/5/2022</td>
            <td>53</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>求求快出签</td>
            <td>F1</td>
            <td>New</td>
            <td>Others</td>
            <td>CS</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>30</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>求快下签</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>ShangHai</td>
            <td>Biostat</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>25</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>Evelyn.Z</td>
            <td>F1</td>
            <td>New</td>
            <td>GuangZhou</td>
            <td>Nutrition Science</td>
            <td>Clear</td>
            <td>12/5/2022</td>
            <td>29</td>
            <td>detail&nbsp;</td>
        </tr>
        <tr>
            <td>SherryZOvO</td>
            <td>F1</td>
            <td>Renewal</td>
            <td>ShangHai</td>
            <td>Mechanical Engineering</td>
            <td>Pending</td>
            <td>12/5/2022</td>
            <td>53</td>
            <td>detail</td>
        </tr>
        <tr>
            <td>快快下签证</td>
            <td>H1</td>
            <td>New</td>
            <td>Toronto</td>
            <td>Information</td>
            <td>Pending</td>
            <td>12/5/2022</td>
            <td>53</td>
            <td>detail</td>
        </tr>
    </table>
);
};

export default TableModule;